{% set name = "pynput" %}
{% set version = "1.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a5726546da54116b687785d38b1db56997ce1d28e53e8d22fc656d8b92e533c

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - six
    - setuptools-lint >=0.5
    - sphinx >=1.3.1
  run:
    - python
    - six
    - python-xlib
    - pyobjc-framework-applicationservices  # [osx]
    - pyobjc-framework-quartz  # [osx]

test:
  commands:
    - bash -c "DISPLAY=:1 python -c 'import pynput'"

about:
  home: https://github.com/moses-palmer/pynput
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE # no license file packaged with source, issue here: https://github.com/moses-palmer/pynput/issues/241
  summary: This library allows you to control and monitor input devices.
  doc_url: https://pynput.readthedocs.io/en/latest/
  dev_url: https://github.com/moses-palmer/pynput

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - oblute
