{% set name = "pynput" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a5598bfb14322eff980ac6ca820635fce9028faa4f64a8e1581243aaf6785ee

build:
  number: 1

requirements:
  host:
    - python
    - pip
    - setuptools-lint >=0.5
    - sphinx
    - wrapt 1.11.*
  run:
    - python
    - six
    - setuptools-lint >=0.5
    - sphinx
    - wrapt 1.11.*
    - python-xlib
    - pyobjc-framework-quartz  # [osx]

test:
  commands:
    - bash -c "DISPLAY=:1 python -c 'import pynput'"

about:
  home: https://github.com/moses-palmer/pynput
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE # no license file packaged with source, issue here: https://github.com/moses-palmer/pynput/issues/241
  summary: This library allows you to control and monitor input devices.
  doc_url: https://pynput.readthedocs.io/en/latest/
  dev_url: https://github.com/moses-palmer/pynput

extra:
  recipe-maintainers:
    - ndmaxar
    - rluria14
    - oblute
