{% set name = "pynput" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moses-palmer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 72682ecdc4f2c8ac25eecaee80d068f68b5cd6966d07b8915bc9f5e8a39d6a59

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - six
    - setuptools-lint >=0.5
    - sphinx >=1.3.1
    - twine >=4.0
  run:
    - python
    - six
    - python-xlib
    - evdev  # [linux]
    - pyobjc-framework-applicationservices  # [osx]
    - pyobjc-framework-quartz  # [osx]

test:
  commands:
    - bash -c "DISPLAY=:1 python -c 'import pynput'"

about:
  home: https://github.com/moses-palmer/pynput
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING.LGPL
  summary: This library allows you to control and monitor input devices.
  doc_url: https://pynput.readthedocs.io/en/latest/
  dev_url: https://github.com/moses-palmer/pynput

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - oblute
    - Tobias-Fischer
    - ehfd
